services:
  php:
    image: php:5.6-fpm
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  nginx_php:
    build: ./docker/nginx
    ports:
      - "5081:8080"
    volumes:
      - ./www:/var/www/html
    environment:
      - MODSEC_RULE_ENGINE=On
    depends_on:
      - php
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

